#!/bin/bash
# gen_vex_v2d.sh -- generate a vex + v2d pair for the fxcorr test bench,
# modelled on datasim's scripts/genv2dvex.sh but templated from the proven
# fxcorr/test/test.vex + test.v2d (SCHED-format vex, VDIF/8032/2 tracks,
# T1/T2 two-station layout), so the output feeds vex2difx -> difxcalc
# unchanged.
#
# usage: gen_vex_v2d.sh <expname> <outdir> [obs_info_file]
#
#   obs_info_file is bash-sourced and may override the defaults below:
#     START         scan start in VEX time format (2020y100d07h00m00s)
#     DURATION_SEC  scan length in seconds (SCHED station line)
#     RA DEC        source coordinates (J2000)
#     ST1_NAME/ST1_POS  station 1 name and site_position "x m: y m: z m"
#     ST2_NAME/ST2_POS  station 2 name and site_position
#     FREQ_MHZ BW_MHZ   band-edge RF frequency and bandwidth
#     FRAMESIZE     VDIF frame size in bytes (8032 for 8Ms/s x 4ms)
#     LO_MHZ1 LO_MHZ2   IF LO frequencies per station
#     EOP_BLOCK     v2d EOP lines (must bracket the scan date; the default
#                   block covers 2020-04-07..11, MJD 58946..58950)
#     CALC          1 = also run vex2difx and difxcalc in the output dir
#
# writes: <outdir>/<expname>.vex  <expname>.v2d  threads
#          (and, with CALC=1: <expname>.input .calc .im .flag .joblist)

set -e

EXPNAME=$1
OUTDIR=$2
OBSINFO=${3:-}

[ -n "$EXPNAME" -a -n "$OUTDIR" ] || {
	echo "usage: gen_vex_v2d.sh <expname> <outdir> [obs_info_file]" >&2
	exit 1
}

# defaults: the fxcorr benchmark experiment (test.vex/test.v2d)
# (each may be overridden via the environment or, later, the obs_info file)
START="${START:-2020y100d07h00m00s}"
DURATION_SEC="${DURATION_SEC:-1200}"
RA="${RA:-01h00m00.0000000s}"
# VEX dec syntax needs the arcmin quote, keep it out of the ${:-} word
# (old bash mis-parses quotes inside the default-value word)
DECDEFAULT='-80d00'"'"'00.000000'
DEC="${DEC:-$DECDEFAULT}"
ST1_NAME="${ST1_NAME:-T1}"
ST1_POS="${ST1_POS:--4751639.85972 m: 2791700.35670 m:-3200491.11339 m}"
ST2_NAME="${ST2_NAME:-T2}"
ST2_POS="${ST2_POS:--4751600.85972 m: 2791700.35670 m:-3200550.11339 m}"
FREQ_MHZ="${FREQ_MHZ:-200.0}"
BW_MHZ="${BW_MHZ:-4.0}"
FRAMESIZE="${FRAMESIZE:-8032}"
LO_MHZ1="${LO_MHZ1:-2000.00}"
LO_MHZ2="${LO_MHZ2:-1600.00}"
CALC="${CALC:-0}"
EOP_DEFAULT=$(cat <<'EOF'
EOP 58946 { xPole=0.056100 yPole=0.409450 tai_utc=37 ut1_utc=-0.230025 }
EOP 58947 { xPole=0.056700 yPole=0.410030 tai_utc=37 ut1_utc=-0.231634 }
EOP 58948 { xPole=0.057490 yPole=0.410990 tai_utc=37 ut1_utc=-0.233215 }
EOP 58949 { xPole=0.058030 yPole=0.412040 tai_utc=37 ut1_utc=-0.234641 }
EOP 58950 { xPole=0.058440 yPole=0.412980 tai_utc=37 ut1_utc=-0.235786 }
EOF
)
EOP_BLOCK="${EOP_BLOCK:-$EOP_DEFAULT}"

[ -n "$OBSINFO" ] && . "$OBSINFO"

mkdir -p "$OUTDIR"

# vex: SCHED-format template from fxcorr/test/test.vex, parameterised
cat > "$OUTDIR/$EXPNAME.vex" <<EOF
VEX_rev = 1.5;
* generated by gen_vex_v2d.sh
\$GLOBAL;
     ref \$EXPER = $EXPNAME;
\$EXPER;
def $EXPNAME;
     exper_name = $EXPNAME;
     exper_description = "fxcorr bench experiment";
     PI_name = "fxcorr";
     target_correlator = DiFX;
enddef;
\$MODE;
def $EXPNAME;
     ref \$PROCEDURES = Mode_01;
     ref \$FREQ = ${FREQ_MHZ}MHz1x${BW_MHZ}MHz:$ST1_NAME:$ST2_NAME;
     ref \$IF = LO@${LO_MHZ1}MHzRPolNoTone:$ST1_NAME;
     ref \$IF = LO@${LO_MHZ2}MHzRPolNoTone:$ST2_NAME;
     ref \$BBC = 1BBCs:$ST1_NAME:$ST2_NAME;
     ref \$TRACKS = VDIF.1Ch2bit:$ST1_NAME:$ST2_NAME;
     ref \$HEAD_POS = LBAVoid:$ST1_NAME:$ST2_NAME;
     ref \$ROLL = NoRoll:$ST1_NAME:$ST2_NAME;
     ref \$PASS_ORDER = LBADummy:$ST1_NAME:$ST2_NAME;
     ref \$PHASE_CAL_DETECT = NoDetect:$ST1_NAME:$ST2_NAME;
enddef;
\$STATION;
def $ST1_NAME;
     ref \$SITE = ${ST1_NAME}SITE;
     ref \$ANTENNA = ${ST1_NAME}SITE;
     ref \$DAS = VDIF;
enddef;
def $ST2_NAME;
     ref \$SITE = ${ST2_NAME}SITE;
     ref \$ANTENNA = ${ST2_NAME}SITE;
     ref \$DAS = VDIF;
enddef;
\$PROCEDURES;
def Mode_01;
     procedure_name_prefix =  "01";
     tape_change =  420 sec;
     headstack_motion =    6 sec;
     new_source_command =    5 sec;
     new_tape_setup =   20 sec;
     setup_always = on :  20 sec;
     parity_check = off : 100 sec;
     tape_prepass = off : 600 sec;
     preob_cal  = on :  10 sec : preob;
     midob_cal  = on :  15 sec : midob;
     postob_cal = on :   0 sec : postob;
enddef;
\$SITE;
def ${ST1_NAME}SITE;
     site_type = fixed;
     site_name = ${ST1_NAME}SITE;
     site_ID = $ST1_NAME;
     site_position = $ST1_POS;
enddef;
def ${ST2_NAME}SITE;
     site_type = fixed;
     site_name = ${ST2_NAME}SITE;
     site_ID = $ST2_NAME;
     site_position = $ST2_POS;
enddef;
\$ANTENNA;
def ${ST1_NAME}SITE;
     axis_type = az : el;
     axis_offset =    0.00000 m;
enddef;
def ${ST2_NAME}SITE;
     axis_type = az : el;
     axis_offset =    0.00000 m;
enddef;
\$DAS;
def VDIF;
     record_transport_type = VDIF;
     electronics_rack_type = VDIF;
     number_drives = 2;
     headstack = 1 :            : 0 ;
     headstack = 2 :            : 1 ;
     tape_motion = adaptive : 0 min: 0 min: 10 sec;
enddef;
\$SOURCE;
def TEST;
     source_name = TEST;
     ra = $RA; dec = ${DEC}"; ref_coord_frame = J2000;
enddef;
\$FREQ;
def ${FREQ_MHZ}MHz1x${BW_MHZ}MHz;
     sample_rate =   8.000 Ms/sec;
     chan_def = :  ${FREQ_MHZ} MHz : U :   ${BW_MHZ} MHz : &CH01 : &BBC01 : &NoCal;
enddef;
\$IF;
def LO@${LO_MHZ1}MHzRPolNoTone;
     if_def = &IF_2N : 2N : R :  ${LO_MHZ1} MHz : U ;
enddef;
def LO@${LO_MHZ2}MHzRPolNoTone;
     if_def = &IF_2N : 2N : R :  ${LO_MHZ2} MHz : U ;
enddef;
\$BBC;
def 1BBCs;
     BBC_assign = &BBC01 :  1 : &IF_2N;
enddef;
\$PHASE_CAL_DETECT;
def NoDetect;
     phase_cal_detect = &NoCal;
enddef;
\$TRACKS;
def VDIF.1Ch2bit;
  track_frame_format = VDIF/${FRAMESIZE}/2;
  fanout_def = A : &CH01 : sign : 1 : 00;
  fanout_def = A : &CH01 : mag  : 1 : 01;
enddef;
\$HEAD_POS;
def LBAVoid;
enddef;
\$PASS_ORDER;
def LBADummy;
     S2_group_order = 0;
enddef;
\$ROLL;
def NoRoll;
     roll = off;
enddef;
\$SCHED;
scan No0001;
     start=$START; mode=$EXPNAME; source=TEST;
     station=$ST1_NAME:    0 sec:  $DURATION_SEC sec:    0.000 GB:   0 :       : 1;
     station=$ST2_NAME:    0 sec:  $DURATION_SEC sec:    0.000 GB:   0 :       : 1;
endscan;
EOF

# v2d: from fxcorr/test/test.v2d
cat > "$OUTDIR/$EXPNAME.v2d" <<EOF
vex=$EXPNAME.vex

maxLength = 86400
maxGap = 86400
maxSize =  1000000
minLength=1

dataBufferFactor = 256
nDataSegments = 64
tweakIntTime = true

antennas = $ST1_NAME, $ST2_NAME

threadsFile = threads
nCore = 1
nThread = 1
startSeries = 0

SETUP default
{
  nChan=4096
  tInt=1
}

ANTENNA $ST1_NAME {
 clockOffset = 0
 phaseCalInt = 0
 file = $ST1_NAME.vdif
}

ANTENNA $ST2_NAME {
 clockOffset = 0
 phaseCalInt = 0
 file = $ST2_NAME-usb.vdif
}

$EOP_BLOCK
EOF

cat > "$OUTDIR/threads" <<EOF
NUMBER OF CORES:    1
1
EOF

echo "wrote $OUTDIR/$EXPNAME.vex, $OUTDIR/$EXPNAME.v2d, $OUTDIR/threads"

if [ "$CALC" = "1" ]; then
	cd "$OUTDIR"
	# DIFXROOT/bin may not be on PATH (non-login shells, containers)
	VEX2DIFX=vex2difx
	DIFXCALC=difxcalc
	command -v vex2difx >/dev/null 2>&1 || VEX2DIFX=${DIFXROOT:-/usr/local/difx}/bin/vex2difx
	command -v difxcalc >/dev/null 2>&1 || DIFXCALC=${DIFXROOT:-/usr/local/difx}/bin/difxcalc
	# vex2difx exits non-zero when it nudges the integration time; the
	# products are still fine, so don't let that abort the chain
	"$VEX2DIFX" "$EXPNAME.v2d" || true
	[ -f "$EXPNAME.input" ] || { echo "vex2difx failed to produce $EXPNAME.input" >&2; exit 1; }
	# difxcalc consumes the .calc (not the .input) and writes the .im
	"$DIFXCALC" "$EXPNAME.calc"
	[ -f "$EXPNAME.im" ] || { echo "difxcalc failed to produce $EXPNAME.im" >&2; exit 1; }
	echo "wrote $EXPNAME.input, $EXPNAME.calc, $EXPNAME.im"
fi
