#!/usr/bin/env python3
"""gen_test_multist.py -- N 站 vex/v2d/threads 生成器（P3 性能剖析/加速比测试资产）

对齐 make_testdata.sh 约定：输出命名 test.vex / test.v2d / threads；预生成到
config/ 后（make_testdata.sh 见 config 资产存在即跳过复制），
vex2difx -> difxcalc -> fxcorr-sim common/station -> fxcorr-f/x 链直接可用。
N=2 时与 fxcorr/test/test.vex + test.v2d 等价（T1/T2 坐标、LO、帧长一致）。

usage: gen_test_multist.py <outdir> [-n N] [-bw BW] [-dur SEC] [-nchan C] [-tint T]

  -n    站数（默认 4）；站名 T1..TN；T1 = test.vex 基准坐标，
        其余沿 (39, 0, -58.92) 每站递增（照 T2 相对 T1 的偏移方向）
  -bw   单 band 带宽 MHz（默认 4）；sample_rate = 2*BW（实采样 Nyquist），
        FRAMESIZE = 32 + 2*BW*1000（VDIF 32B 头 + 4ms 帧数据，BW=4 -> 8032）
  -dur  scan 时长秒（默认 1200）
  -nchan/tint  v2d SETUP 的 nChan / tInt（默认 4096 / 1）
"""

import argparse
import sys

EOP_BLOCK = """\
EOP 58946 { xPole=0.056100 yPole=0.409450 tai_utc=37 ut1_utc=-0.230025 }
EOP 58947 { xPole=0.056700 yPole=0.410030 tai_utc=37 ut1_utc=-0.231634 }
EOP 58948 { xPole=0.057490 yPole=0.410990 tai_utc=37 ut1_utc=-0.233215 }
EOP 58949 { xPole=0.058030 yPole=0.412040 tai_utc=37 ut1_utc=-0.234641 }
EOP 58950 { xPole=0.058440 yPole=0.412980 tai_utc=37 ut1_utc=-0.235786 }"""

# T1 = test.vex 基准坐标；T2-T1 = (39.0, 0, -58.92)
T1_POS = (-4751639.85972, 2791700.35670, -3200491.11339)
DELTA = (39.0, 0.0, -58.92)
START = "2020y100d07h00m00s"
RA = "01h00m00.0000000s"
DEC = "-80d00'00.000000"
LO_MHZ = 2000.00


def site_pos(k):
    x, y, z = T1_POS
    dx, dy, dz = DELTA
    return (x + k * dx, y + k * dy, z + k * dz)


def gen_vex(nstations, bw, dur):
    stations = ["T%d" % (i + 1) for i in range(nstations)]
    sref = ":".join(stations)
    sample_rate = 2.0 * bw
    framesize = 32 + 2 * bw * 1000

    lines = []
    lines.append("VEX_rev = 1.5;")
    lines.append("* generated by gen_test_multist.py")
    lines.append("$GLOBAL;")
    lines.append("    ref $EXPER = multist;")
    lines.append("$EXPER;")
    lines.append("def multist;")
    lines.append('    exper_name = multist;')
    lines.append('    exper_description = "fxcorr P3 bench experiment";')
    lines.append('    PI_name = "fxcorr";')
    lines.append("    target_correlator = DiFX;")
    lines.append("enddef;")
    lines.append("$MODE;")
    lines.append("def multist;")
    lines.append("    ref $PROCEDURES = Mode_01;")
    lines.append("    ref $FREQ = %.1fMHz1x%.1fMHz:%s;" % (200.0, bw, sref))
    for st in stations:
        lines.append("    ref $IF = LO@%.2fMHzRPolNoTone:%s;" % (LO_MHZ, st))
    lines.append("    ref $BBC = 1BBCs:%s;" % sref)
    lines.append("    ref $TRACKS = VDIF.1Ch2bit:%s;" % sref)
    lines.append("    ref $HEAD_POS = LBAVoid:%s;" % sref)
    lines.append("    ref $ROLL = NoRoll:%s;" % sref)
    lines.append("    ref $PASS_ORDER = LBADummy:%s;" % sref)
    lines.append("    ref $PHASE_CAL_DETECT = NoDetect:%s;" % sref)
    lines.append("enddef;")
    lines.append("$STATION;")
    for st in stations:
        lines.append("def %s;" % st)
        lines.append("    ref $SITE = %sSITE;" % st)
        lines.append("    ref $ANTENNA = %sSITE;" % st)
        lines.append("    ref $DAS = VDIF;")
        lines.append("enddef;")
    lines.append("$PROCEDURES;")
    lines.append("def Mode_01;")
    lines.append('    procedure_name_prefix =  "01";')
    lines.append("    tape_change =  420 sec;")
    lines.append("    headstack_motion =    6 sec;")
    lines.append("    new_source_command =    5 sec;")
    lines.append("    new_tape_setup =   20 sec;")
    lines.append("    setup_always = on :  20 sec;")
    lines.append("    parity_check = off : 100 sec;")
    lines.append("    tape_prepass = off : 600 sec;")
    lines.append("    preob_cal  = on :  10 sec : preob;")
    lines.append("    midob_cal  = on :  15 sec : midob;")
    lines.append("    postob_cal = on :   0 sec : postob;")
    lines.append("enddef;")
    lines.append("$SITE;")
    for k, st in enumerate(stations):
        x, y, z = site_pos(k)
        lines.append("def %sSITE;" % st)
        lines.append("    site_type = fixed;")
        lines.append("    site_name = %sSITE;" % st)
        lines.append("    site_ID = %s;" % st)
        lines.append("    site_position = %.5f m: %.5f m: %.5f m;" % (x, y, z))
        lines.append("enddef;")
    lines.append("$ANTENNA;")
    for st in stations:
        lines.append("def %sSITE;" % st)
        lines.append("    axis_type = az : el;")
        lines.append("    axis_offset =    0.00000 m;")
        lines.append("enddef;")
    lines.append("$DAS;")
    lines.append("def VDIF;")
    lines.append("    record_transport_type = VDIF;")
    lines.append("    electronics_rack_type = VDIF;")
    lines.append("    number_drives = 2;")
    lines.append("    headstack = 1 :            : 0 ;")
    lines.append("    headstack = 2 :            : 1 ;")
    lines.append("    tape_motion = adaptive : 0 min: 0 min: 10 sec;")
    lines.append("enddef;")
    lines.append("$SOURCE;")
    lines.append("def TEST;")
    lines.append("    source_name = TEST;")
    lines.append("    ra = %s; dec = %s\"; ref_coord_frame = J2000;" % (RA, DEC))
    lines.append("enddef;")
    lines.append("$FREQ;")
    lines.append("def %.1fMHz1x%.1fMHz;" % (200.0, bw))
    lines.append("    sample_rate =   %.3f Ms/sec;" % sample_rate)
    lines.append("    chan_def = :  200.000 MHz : U :   %.3f MHz : &CH01 : &BBC01 : &NoCal;" % bw)
    lines.append("enddef;")
    lines.append("$IF;")
    lines.append("def LO@%.2fMHzRPolNoTone;" % LO_MHZ)
    lines.append("    if_def = &IF_2N : 2N : R :  %.2f MHz : U ;" % LO_MHZ)
    lines.append("enddef;")
    lines.append("$BBC;")
    lines.append("def 1BBCs;")
    lines.append("    BBC_assign = &BBC01 :  1 : &IF_2N;")
    lines.append("enddef;")
    lines.append("$PHASE_CAL_DETECT;")
    lines.append("def NoDetect;")
    lines.append("    phase_cal_detect = &NoCal;")
    lines.append("enddef;")
    lines.append("$TRACKS;")
    lines.append("def VDIF.1Ch2bit;")
    lines.append("  track_frame_format = VDIF/%d/2;" % framesize)
    lines.append("  fanout_def = A : &CH01 : sign : 1 : 00;")
    lines.append("  fanout_def = A : &CH01 : mag  : 1 : 01;")
    lines.append("enddef;")
    lines.append("$HEAD_POS;")
    lines.append("def LBAVoid;")
    lines.append("enddef;")
    lines.append("$PASS_ORDER;")
    lines.append("def LBADummy;")
    lines.append("     S2_group_order = 0;")
    lines.append("enddef;")
    lines.append("$ROLL;")
    lines.append("def NoRoll;")
    lines.append("     roll = off;")
    lines.append("enddef;")
    lines.append("$SCHED;")
    lines.append("scan No0001;")
    lines.append("    start=%s; mode=multist; source=TEST;" % START)
    for st in stations:
        lines.append("    station=%s:    0 sec:  %d sec:    0.000 GB:   0 :       : 1;" % (st, dur))
    lines.append("endscan;")
    return "\n".join(lines) + "\n"


def gen_v2d(nstations, nchan, tint):
    stations = ["T%d" % (i + 1) for i in range(nstations)]
    lines = []
    lines.append("vex=test.vex")
    lines.append("")
    lines.append("maxLength = 86400")
    lines.append("maxGap = 86400")
    lines.append("maxSize =  1000000")
    lines.append("minLength=1")
    lines.append("")
    lines.append("dataBufferFactor = 256")
    lines.append("nDataSegments = 64")
    lines.append("tweakIntTime = true")
    lines.append("")
    lines.append("antennas = %s" % ", ".join(stations))
    lines.append("")
    lines.append("threadsFile = threads")
    lines.append("nCore = 1")
    lines.append("nThread = 1")
    lines.append("startSeries = 0")
    lines.append("")
    lines.append("SETUP default")
    lines.append("{")
    lines.append("  nChan=%d" % nchan)
    lines.append("  tInt=%d" % tint)
    lines.append("}")
    lines.append("")
    for st in stations:
        lines.append("ANTENNA %s {" % st)
        lines.append("  clockOffset = 0")
        lines.append("  phaseCalInt = 0")
        lines.append("  file = %s.vdif" % st)
        lines.append("}")
        lines.append("")
    lines.append(EOP_BLOCK)
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir")
    ap.add_argument("-n", type=int, default=4, dest="nstations")
    ap.add_argument("-bw", type=float, default=4.0)
    ap.add_argument("-dur", type=int, default=1200)
    ap.add_argument("-nchan", type=int, default=4096)
    ap.add_argument("-tint", type=int, default=1)
    args = ap.parse_args()

    if args.nstations < 2:
        sys.exit("gen_test_multist.py: -n must be >= 2")

    with open(args.outdir + "/test.vex", "w") as f:
        f.write(gen_vex(args.nstations, args.bw, args.dur))
    with open(args.outdir + "/test.v2d", "w") as f:
        f.write(gen_v2d(args.nstations, args.nchan, args.tint))
    with open(args.outdir + "/threads", "w") as f:
        f.write("NUMBER OF CORES:    1\n1\n")

    print("wrote %s/test.vex test.v2d threads (%d stations, bw=%.1fMHz, dur=%ds, nChan=%d)"
          % (args.outdir, args.nstations, args.bw, args.dur, args.nchan))


if __name__ == "__main__":
    main()
